# Generated by Django 4.1.7 on 2023-04-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giocatore',
            name='assist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='fanta_media',
            field=models.FloatField(default=6.0),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='gol',
            field=models.IntegerField(default=0),
        ),
    ]
