# Generated by Django 4.1.7 on 2023-04-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0004_giocatore_posizione'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiocatorePartita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gol', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcetto.giocatore')),
            ],
        ),
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('punteggio_totale', models.IntegerField()),
                ('giocatori', models.ManyToManyField(through='calcetto.GiocatorePartita', to='calcetto.giocatore')),
            ],
        ),
        migrations.AddField(
            model_name='giocatorepartita',
            name='partita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcetto.partita'),
        ),
    ]
