# Generated by Django 4.1.7 on 2023-04-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0005_giocatorepartita_partita_giocatorepartita_partita'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GiocatorePartita',
            new_name='Partecipazione',
        ),
    ]
