# Generated by Django 4.1.7 on 2023-04-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0006_rename_giocatorepartita_partecipazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partita',
            name='punteggio_totale',
            field=models.CharField(max_length=50),
        ),
    ]
