# Generated by Django 4.1.7 on 2023-04-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0002_giocatore_assist_giocatore_fanta_media_giocatore_gol'),
    ]

    operations = [
        migrations.AddField(
            model_name='giocatore',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
