# Generated by Django 4.1.7 on 2023-04-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0009_profilo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partita',
            name='punteggio_totale',
        ),
        migrations.AddField(
            model_name='partita',
            name='punteggio_squadra_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partita',
            name='punteggio_squadra_b',
            field=models.IntegerField(default=0),
        ),
    ]
