# Generated by Django 4.1.7 on 2023-04-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcetto', '0010_remove_partita_punteggio_totale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partita',
            name='giocatori',
        ),
        migrations.AddField(
            model_name='partita',
            name='partecipazioni',
            field=models.ManyToManyField(blank=True, through='calcetto.Partecipazione', to='calcetto.giocatore'),
        ),
        migrations.AddField(
            model_name='partita',
            name='squadra_a',
            field=models.ManyToManyField(blank=True, related_name='partite_squadra_a', to='calcetto.giocatore'),
        ),
        migrations.AddField(
            model_name='partita',
            name='squadra_b',
            field=models.ManyToManyField(blank=True, related_name='partite_squadra_b', to='calcetto.giocatore'),
        ),
    ]
